# Generated by Django 4.2.6 on 2023-10-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bwc_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='active',
            field=models.BooleanField(),
        ),
    ]
